services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    platform: linux/amd64
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    platform: linux/amd64
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  postgres:
    image: postgres:15
    platform: linux/amd64
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7362170Mm.
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    platform: linux/amd64
    ports:
      - "6000:6000"
    depends_on:
      - kafka
      - postgres
    environment:
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=postgresql://postgres:7362170Mm.@postgres:5432/social_app_auth_db
    volumes:
      - ./auth-service:/app

  user-service:
    build: ./user-service
    platform: linux/amd64
    ports:
      - "6001:6001"
    depends_on:
      - kafka
      - postgres
    environment:
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=postgresql://postgres:7362170Mm.@postgres:5432/social_app_user_db
    volumes:
      - ./user-service:/app

  follow-service:
    build: ./follow-service
    platform: linux/amd64
    ports:
      - "6003:6003"
    depends_on:
      - kafka
      - postgres
    environment:
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=postgresql://postgres:7362170Mm.@postgres:5432/social_app_follow_db
    volumes:
      - ./follow-service:/app

volumes:
  pgdata: